### ISSUE TITLE
[Kahla.App][v3.3.1]Failed to install the app.

### ISSUE THREAD

**Issue by 44asad** [AiursoftWeb/Kahla#487] opened 2019-05-22 12:30 UTC
#### Actual Behaviour

App fail to install in my device.
#### Expected Behaviour

I expected that i can install and use the app successfully.
#### Step to reproduce
* Download the app from release page
* click the app to install
* see the error
#### Information
App version:v3.3.1
Os:Android 6.0.1
Device:Samsung j5 
#### Recording of the bug

https://youtu.be/22AiFXTkerM

**Comment by Anduin2017** [comment] 2019-05-22 15:41
Got it. Will fix. 

While we are trying to repro this, please try Android with later version like Android 9.

**Comment by Anduin2017** [comment] 2019-05-24 03:38
@xxyzz Hi, shall we downgrade our Apache Cordova version to support Android 6? It seems our current version already supports Android 6.0. See here:

https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#requirements-and-support

So what's the problem then?

**Comment by xxyzz** [comment] 2019-05-24 03:53
```
$ export ORG_GRADLE_PROJECT_cdvMinSdkVersion=23
$ cordova build android
// or
$ cordova run android -- --gradleArg=-PcdvMinSdkVersion=23
```
These commands will overrides the default value of `minSdkVersion` set in `AndroidManifest.xml` according to the document.

The problem is finding an Android 6 phone.

**Comment by 44asad** [comment] 2019-05-24 03:56
yes!my Android  6.0.1 phone problem.

**Comment by Anduin2017** [comment] 2019-05-25 04:53
@xxyzz So, any suggestions to support more platforms for Kahla APK?

**Comment by xxyzz** [comment] 2019-05-25 06:03
Use the above commands? But I only have Android 8 and 9 phones.

**Comment by Anduin2017** [comment] 2019-05-25 06:13
@xxyzz Our current build script is:

```bash
echo 'Installling latest cordova...'
npm i -g cordova@latest

echo 'Adding android platform...'
cordova platform add android

echo 'Downloading keys...'
curl https://oss.aiursoft.com/download/fromsecret?sec={KEY} --output - > android.jks

echo 'Building with cordova...'
cordova build android --release -- --keystore=./android.jks --storePassword={KEY} --alias=key0 --password={PASSWORD}

PACKAGE_VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g')

echo $PACKAGE_VERSION

PACKAGE_VERSION_TRIM="$(echo -e "${PACKAGE_VERSION}" | tr -d '[:space:]')"

mv ./platforms/android/app/build/outputs/apk/release/app-release.apk ./platforms/android/app/build/outputs/apk/release/Kahla-Android-$PACKAGE_VERSION_TRIM.apk 
```
How shall we change this?

**Comment by xxyzz** [comment] 2019-05-25 06:18
Add `export ORG_GRADLE_PROJECT_cdvMinSdkVersion=19` above `cordova build android` should works, it will build apk supports Android 4.4.

**Comment by Anduin2017** [comment] 2019-05-25 06:22
Scheduled a new build. Please try again 30 minutes later. @44asad 

Just download again the master build. The build shall be finished at about 2:50 pm 5/25/2019.

**Comment by 44asad** [comment] 2019-06-02 22:02
ok

**Comment by Anduin2017** [comment] 2019-06-03 02:47
@44asad  Please tell me if the issue was fixed. Thanks!

**Comment by Anduin2017** [comment] 2019-06-12 05:35
@xxyzz It seems that the solution you mentioned did not solve this. I suppose that we need to continue diagnostics this.

**Comment by Anduin2017** [comment] 2019-06-16 18:21
As @Xiangrui2019 suggested, this may impact this issue:

https://github.com/AiursoftWeb/Kahla.App/blob/32c86df95c73d1b2070add615b072361c4133604/config.xml#L49

Shall we investigate this? @AiursoftWeb/kahla-team 

If downgrading this will help, I suggest supporting Android 5 and above. But right now it was hard for me to test on a really old machine.

**Comment by Anduin2017** [comment] 2019-06-17 12:27
@Xiangrui2019  It seems that the problem was not there.

https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#requirements-and-support


cordova-android Version | Supported Android API-Levels | Equivalent Android Version
-- | -- | --
8.X.X | 19 - 28 | 4.4 - 9.0.0
7.X.X | 19 - 27 | 4.4 - 8.1
6.X.X | 16 - 26 | 4.1 - 8.0.0
5.X.X | 14 - 23 | 4.0 - 6.0.1
4.1.X | 14 - 22 | 4.0 - 5.1
4.0.X | 10 - 22 | 2.3.3 - 5.1
3.7.X | 10 - 21 | 2.3.3 - 5.0.2

Now our Cordova android engine is 7.1.4. Which supports android 4.4 - 8.1.

But that seems strange. Can you help us diagnostic this?

**Comment by hv0905** [comment] 2019-06-18 08:01
Have we tried to add this preference into `config.xml`?
```
<platform name="android">
    . . .
    <preference name="android-minSdkVersion" value="19"/>
    . . .
</platform>
```

**Comment by Anduin2017** [comment] 2019-06-18 08:14
It seems much more strange now. As @hv0905  mentioned, the package was already supported with android api level 19.

![6548](https://user-images.githubusercontent.com/19531547/59664694-19077180-91e4-11e9-89d4-47d74ad17b93.png)

**Comment by hv0905** [comment] 2019-06-21 07:03
Should be fixed in 8039c000cef44e059ec67a89fbfa9489cdc7c7e3, @FNAC-Z @44asad  please try the newest production build and tell us if the problem still exists.

**Comment by Anduin2017** [comment] 2019-06-21 07:06
While this issue was fixed, the layout still looks awful. Let's keep this issue open if more layout issue reports.

**Comment by FNAC-Z** [comment] 2019-06-21 08:03
Thank you, the problem has been solved.

**Closed as completed** 2019-07-05 04:51 UTC
Labels: Invalid design
